server:
  port: 8080

rest:
  auth-open : true # 如果为true，则开启JWT的验证

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  md5-key: randomKey      #md5加密混淆key

mybatis-plus:
  mapper-locations: classpath*:com/next/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootfile?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.next.jiangzh: debug
  path: logs/
  file: next-film.log


film:
  img-pre: http://img.nextfilm.cn/

order:
  file-path-pre : F:/workSpace/next_workspace/imags/
  alipay-callback-path : http://nextfilm.natapp1.cc/order/alipay/callback